# Generated by Django 5.2.17 on 2026-10-03 10:54

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DiagnosticCentre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("address", models.CharField(max_length=300)),
                ("city", models.CharField(db_index=True, max_length=100)),
                ("pincode", models.CharField(max_length=10)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DiagnosticTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        help_text="Short unique code, e.g. CBC",
                        max_length=30,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CentreTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_available", models.BooleanField(default=True)),
                (
                    "centre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offerings",
                        to="catalog.diagnosticcentre",
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offerings",
                        to="catalog.diagnostictest",
                    ),
                ),
            ],
            options={
                "ordering": ["test__name"],
            },
        ),
        migrations.AddField(
            model_name="diagnosticcentre",
            name="tests",
            field=models.ManyToManyField(
                related_name="centres",
                through="catalog.CentreTest",
                to="catalog.diagnostictest",
            ),
        ),
        migrations.AddConstraint(
            model_name="diagnosticcentre",
            constraint=models.UniqueConstraint(
                fields=("name", "city"), name="unique_centre_name_per_city"
            ),
        ),
        migrations.AddConstraint(
            model_name="centretest",
            constraint=models.UniqueConstraint(
                fields=("centre", "test"), name="unique_test_per_centre"
            ),
        ),
        migrations.AddConstraint(
            model_name="centretest",
            constraint=models.CheckConstraint(
                condition=models.Q(("price__gt", Decimal("0"))),
                name="centre_test_price_positive",
            ),
        ),
    ]
