# Generated by Django 5.2.17 on 2026-10-03 10:54

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("appointment_at", models.DateTimeField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="INR", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending payment"),
                            ("CONFIRMED", "Confirmed"),
                            ("FAILED", "Payment failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "centre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="catalog.diagnosticcentre",
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="catalog.diagnostictest",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"], name="booking_user_created_idx"
                    ),
                    models.Index(fields=["status"], name="booking_status_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("amount__gt", Decimal("0"))),
                        name="booking_amount_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "status__in",
                                ["PENDING", "CONFIRMED", "FAILED", "CANCELLED"],
                            )
                        ),
                        name="booking_status_valid",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("status__in", ["PENDING", "CONFIRMED"])),
                        fields=("user", "centre", "test", "appointment_at"),
                        name="unique_active_booking_per_slot",
                    ),
                ],
            },
        ),
    ]
